uav_names: ["uav1", "uav2", "uav3", "uav4", "uav5", "uav6", "uav7", "uav8", "uav9", "uav10"]

# odometry_topic: "estimation_manager/ground_truth/odom"
odometry_topic: "estimation_manager/odom_main"

set_reference_timer:
  rate: 10 # [Hz]

diagnostics:
  rate: 0.5 # [Hz]
  odom_timeout: 1.0 # [s]

odom_msg_max_latency: 1.0 # [s]

# control approach params
controlled_dimensions: 3


d1: 0.3
d2: 0.3
d3: 0.3
d4: 0.3
radius: 1.5
encumbrance: 0.5
betaD: 0.5
beta_min: 0.5
dt: 0.01
step_size: 0.1


