uav_names: ["uav1", "uav2", "uav3", "uav4", "uav5", "uav6"]

# odometry_topic: "estimation_manager/ground_truth/odom"
odometry_topic: "estimation_manager/odom_main"

set_reference_timer:
  rate: 10 # [Hz]
