# the connecting root frame will be named like this
connecting_frame_id: "common_origin"

# these are the tf subtrees to be connected through the respective root frames so that the equal frames are equal
connections:
  - root_frame_id: "uav1/fcu"
    equal_frame_id: "uav1/gps_origin"

  - root_frame_id: "uav2/fcu"
    equal_frame_id: "uav2/gps_origin"

  - root_frame_id: "uav3/fcu"
    equal_frame_id: "uav3/gps_origin"

  - root_frame_id: "uav7/fcu"
    equal_frame_id: "uav7/gps_origin"

  - root_frame_id: "uav8/fcu"
    equal_frame_id: "uav8/gps_origin"

  - root_frame_id: "uav13/fcu"
    equal_frame_id: "uav13/gps_origin"
    #
  # you can add further connections here:
  # - root_frame_id: "another_root"
  #   equal_frame_id: "another_equal"

# if true, older messages than the last update of the respective frame connection will be ignored
ignore_older_messages: false

# if no update of a certain connection happens for this duration, it will be forced
max_update_period: 0.1 # seconds (set to zero to disable)
